import { z } from 'zod';

export const personelSchema = z.object({
    // ✅ Zorunlu Alanlar
    adi: z.string().min(2, "Ad en az 2 karakter olmalı"),
    soyadi: z.string().min(2, "Soyad en az 2 karakter olmalı"),
    kk: z.number().int().positive("Geçerli bir TC Kimlik Numarası girin"),
    kts: z.date({ message: "Geçerli bir kayıt tarihi seçin" }),

    // 🟡 İsteğe Bağlı Alanlar
    tc_kimlik_no: z.number().optional(),
    sicil_no: z.string().optional(),
    siralama_kodu: z.number().optional(),
    cinsiyeti: z.enum(['Erkek', 'Kadın']).optional(),
    dogum_tarihi: z.date().optional(),
    kadro_turu: z.number().optional(),
    unvan_id: z.number().optional(),
    brans_id: z.number().optional(),
    gorev_id: z.number().optional(),
    durum_id: z.number().optional(),
    birim_id: z.number().optional(),
    dis_kurum_id: z.number().optional(),
    part_time: z.number().int().optional().default(0),
    part_time_tarihi: z.date().optional(),
    otomasyon_kod: z.string().optional(),
    kisa_unvani: z.string().optional(),
    ise_baslama_tarihi: z.date().optional(),
    cep_telefonu: z.string().optional(),
    eposta: z.string().email("Geçerli bir e-posta girin").optional(),
    ev_adresi1: z.string().optional(),
    ev_adresi2: z.string().optional(),
    ev_posta_kodu: z.string().optional(),
    ev_telefonu: z.string().optional(),
    acil_ulasilacak_kisi: z.string().optional(),
    acil_ulasilacak_tel: z.string().optional(),
    vergi_dairesi: z.string().optional(),
    vergi_no: z.string().optional(),
    baba_adi: z.string().optional(),
    ana_adi: z.string().optional(),
    dogum_yeri: z.string().optional(),
    medeni_hal_kodu: z.number().optional(),
    kimlik_kart_seri: z.string().optional(),
    kimlik_kart_no: z.string().optional(),
    kimlik_il_id: z.number().optional(),
    kimlik_ilce_id: z.number().optional(),
    kimlik_mahalle: z.string().optional(),
    kimlik_verildigi_yer: z.string().optional(),
    kimlik_verilis_tarihi: z.date().optional(),
    kan_grubu_id: z.number().optional(),
    banka_id: z.number().optional(),
    banka_hesap_no: z.string().optional(),
    iban_no: z.string().optional(),
    mezuniyet_tarihi: z.date().optional(),
    mezun_oldugu_okul: z.string().optional(),
    sendika_id: z.number().optional(),
    sendika_giris_tarihi: z.date().optional(),
    sendika_cikis_tarihi: z.date().optional(),
    web_parolasi: z.string().optional(),
    webde_goster: z.number().int().optional().default(0),
    adres_tipi: z.number().optional(),
    adres_kodu_seviyesi: z.number().optional(),
    calisma_planinda_goster: z.number().int().optional(),
    saramatik_resim_goster: z.number().int().optional().default(1),
    lios_kullanici: z.string().optional(),
    lios_sifre: z.string().optional(),
    butce_turu: z.string().optional(),

    // ❗️Diğer tüm alanlar da buraya eklenebilir
}).required({
    adi: true,
    soyadi: true,
    kk: true,
    kts: true,
});