// src/modules/Personel/types/personel.ts

export interface PersonelFormData {
    adi: string;
    soyadi: string;
    tc_kimlik_no: number | undefined;
    dogum_tarihi: Date | string | undefined;
    cinsiyet_adi: string;
    birim_adi: string;
    unvan_adi: string;
    gorev_adi: string;
    durum_adi: string;
    cep_telefonu: string;
    eposta: string;
    ev_adresi1: string;
    ev_adresi2: string;
    ev_telefonu: string;
    acil_ulasilacak_kisi: string;
    acil_ulasilacak_tel: string;
    vergi_dairesi: string;
    web_parolasi: string;
    siralama_kodu: number | undefined;
    medeni_hal_kodu: number | undefined;
    kadro_turu: number | undefined;
    kan_grubu_id: number | undefined;
    kimlik_kart_seri: string;
    kimlik_kart_no: string;
    kimlik_il_id: number | undefined;
    kimlik_ilce_id: number | undefined;
    kimlik_mahalle: string;
    kimlik_verildigi_yer: string;
    kimlik_verilis_tarihi: Date | string | undefined;
    kimlik_cilt_no: string;
    kimlik_aile_sira_no: string;
    kimlik_sira_no: string;
    kimlik_kayit_no: string;
    part_time: number | undefined;
    part_time_tarihi: Date | string | undefined;
    cikis_tarihi: Date | string | undefined;
    cikis_turu_id: number | undefined;
    cikis_aciklama: string;
    cikis_atama_yeri: string;
    banka_id: number | undefined;
    banka_hesap_no: string;
    iban_no: string;
    banka_sube_no: string;
    banka_sube_no2: string;
    ek_banka_hesap_no: string;
    mezun_oldugu_okul: string;
    diploma_no: string;
    diploma_tescil_tarihi: Date | string | undefined;
    uzmanlik_tarihi: Date | string | undefined;
    profesor_tarihi: Date | string | undefined;
    ogrenim_durumu_id: number | undefined;
    bildigi_diller: string;
    dis_kurum_id: number | undefined;
    sendika_id: number | undefined;
    sendika_giris_tarihi: Date | string | undefined;
    sendika_cikis_tarihi: Date | string | undefined;
    cocuk_sayisi: number | undefined;
    nvi_onayli: number | undefined;
    arsiv_no: number | undefined;
    mazeret_durum_id: number | undefined;
    engelli_kisi: number | undefined;
    ozur_orani: number | undefined;
    kutuk_no: string;
    kurumdisi_ekodeme: number | undefined;
}